### ISSUE TITLE
api/add-profile accepts empty profile

### ISSUE THREAD

**Issue by ceroloy** [otsimo/api#2]
Trying to add an empty profile does not return any error.	
 	

	tests := []struct {
		p   *apipb.Profile
		err error
	}{
		{
			p: &apipb.Profile{
				Id: bson.ObjectIdHex("000000000000000000000002"),
				Email:"c@g.com",
				FirstName: "c",
				LastName: "g",
				CreatedAt:millisecondsNow(),
				LastUpdated:millisecondsNow(),
			},
		},
		{
			p: &apipb.Profile{
				Id: bson.ObjectIdHex("000000000000000000000002"),
				Email:"someone@somewhere.com",
				FirstName: "Some",
				LastName: "One",
				CreatedAt:millisecondsNow(),
				LastUpdated:millisecondsNow(),

			},
		},
		{
			p: &apipb.Profile{
				Id: bson.ObjectIdHex("000000000000000000000002"),
				Email:"someone@somewhere.com",
				FirstName: "Some",
				LastName: "One",
				CreatedAt:millisecondsNow(),
				LastUpdated:millisecondsNow(),

			},
			err: grpc.Errorf(2, "ID already exists"),
		},
		{
			p: &apipb.Profile{},
			err: grpc.Errorf(2, "Invalid ID"),
		},
	}

	for i, tt := range tests {
		_, err := apiClient.AddProfile(context.Background(), tt.p)
		if err != tt.err {
			t.Fatalf("case %d, expected %v, got %v", i, tt.err, err)
		}
	}

 --- FAIL: TestAddProfile (0.02s)
	apipb_test.go:89: case 3, expected rpc error: code = 2 desc = "Invalid ID", got nil

**Comment by sercand** [comment]
fixed
